name: Build
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        uses: mstksg/get-package@master
        with:
                apt-get: make expat libopenscap8 libxml2-utils ninja-build python3-jinja2 python3-yaml xsltproc
      - name: Make
        run: |
          make clean all
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Automated content rebuild
          title: 'Automated build of ComplianceAsContent/content rhel8'
          body: |
            Automated content re-build.
          committer: Github Actions Automation <isimluk@fedorapeople.org>
          author: Github Actions Automation <isimluk@fedorapeople.org>
          branch: update-rebuild
          branch-suffix: short-commit-hash
          reviewers: isimluk
          base: master
      - name: Check output environment variable
        run: echo "Pull Request Number - $PULL_REQUEST_NUMBER"
